/* DO NOT EDIT THIS FILE - it is machine generated */
//#include "jni.h"
#include <jni.h>
/* Header for class others_myJNIHelloWorld */

#ifndef _Included_others_myJNIHelloWorld
#define _Included_others_myJNIHelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     others_myJNIHelloWorld
 * Method:    DisplayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_others_myJNIHelloWorld_DisplayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
